Develop
maypink/ML-algorithms pull request #1
Opened 2021-12-08 11:28 UTC by maypink

2021-12-11 11:35 UTC, ARQtty requested changes

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def check_min_leaf_size(sample1: pd.DataFrame, sample2: pd.DataFrame):
такое лучше делать с помощью assert

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def check_restrictions(self):
любые проверки лучше делать в виде check or throw. Ловить ошибку лучше, чем проверять булевы условия. Так что ассерты лучше

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +                self.add_node(sample1, ' [< ', split_feature, best_t, None, node['parents'] + [node['name']])
тут лучше именовать параметры. Иначе непонятно что зачем. То есть

`self.add_node(sample=sample, sign=' [< ' .... `

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def add_node(self, sample: pd.DataFrame, sign: str, split_feature: str, best_t: float, edges: List[str] = None,
кажется, что ты всегда добавляешь по две ноды. Тогда может стоит 
1. сделать add_node приватным
2. добавить метод, который добавляет сразу две ноды. В него инкапсулировать эти странные параметры sign, чтобы не указывать их самой. И другую неочевидную работу при создании нод

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +                    if sign == '>=':
У `if sign == '>=':` нет else'а. Зачем этот if?

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def check_on_edges(self, sample: pd.DataFrame, edges: List[str]):
не хватает комментов к методам

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +                if node['name'] == edge:
глубокая вложенность - это всегда плохо. Чтобы избавиться, инвертируй условия. 

Например, избавиться от вложенности `if node['name'] == edge:` можно, если написать

```
if node['name'] != edge:
   continue
```
далее будет идти код, обрабатывающий ситуацию `if node['name'] == edge:`. Вложенность не увеличится

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +                        elif node['edges'] == None:
в питоне лучше проверять `var is None`

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +                        if (sample[feature] < t) & (node['edges'] != None):
в питоне лучше использовать `and` вместо `&`

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/funcs.py
> +def entropy(y):
типы

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/funcs.py
> +def weighted_entropy(root_size, subset):
типы

2021-12-11 11:35 UTC, ARQtty commented on DecisionTree/funcs.py
> +    entropy = sum(probabilities * -np.log2(probabilities))
а если один из элементов probabilities - 0? Надо обработать эту ситуацию. Если в этом массиве все элементы [0; 1], то можно добавлять очень малое eps

2021-12-11 11:35 UTC, ARQtty commented on LinearRegression/linreg.py
> +    def check_stop_criteria(self, old_weights: np.ndarray,
такие имена функций-проверок плохи тем, что создают неинтуитивный код. Например ты напишешь 

`if self.check_stop_criteria(...):`, и будет неясно, что должно быть дальше. Какая-то сложная логика. Можно упростить. Например назвать метод is_should_stop(). По `is_` сразу ясно, что это булева функция. Остальная часть названия говорит о том, что сделать, если функция вернула true. 

`if self.is_should_stop(...):` - сразу понятно, что нужно сделать

2021-12-11 11:35 UTC, ARQtty commented on LinearRegression/linreg.py
> +    def _count_grad(features, labels, preds):
типы

2021-12-11 11:35 UTC, ARQtty commented on LinearRegression/linreg.py
> +    def load_weights(self, path: Path) -> None:
эта функция должна создавать обученную модель. Тогда это можно сделать classmethod'ом. Почитай про этот декоратор. В данном случае можно назвать метод `from_pickle` например. Тогда сразу будет понятно, из чего создается, что принимает на вход и что делает метод

2021-12-11 11:35 UTC, ARQtty commented on LinearRegression/linreg.py
> +    def save_weights(self, path: Path) -> None:
по аналогии с from_pickle, можно назвать to_pickle. Тогда будет понятно, что это пара методов, которые сделаны друг для друга. Сразу проще воспринимать код

2021-12-14 22:25 UTC, maypink commented on DecisionTree/funcs.py
> +    entropy = sum(probabilities * -np.log2(probabilities))
автор был умнее хлопотова и исправлял его функции

2021-12-14 22:25 UTC, maypink commented on DecisionTree/funcs.py
> +    entropy = sum(probabilities * -np.log2(probabilities))
не сарказм, если что

2021-12-14 23:46 UTC, ARQtty requested changes

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def check_min_leaf_size(sample1: pd.DataFrame, sample2: pd.DataFrame):
не хочешь assert'ы?

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def check_restrictions(self):
не хочешь кидать ошибку?

2021-12-14 23:46 UTC, ARQtty commented on LinearRegression/linreg.py
> +class LinearRegression:
имена модулей - snake_case
имена файлов - такие же как имена классов в них (но файлы в snake_case. Например тут будет linear_regression.py)

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +            try:
будет проще и понятнее:
```
try:
 self.check_or_throw_restrictions()
except AssertionError:
 break
```

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +            if (node['edges'] == None) & (entropy(node['df']['species']) != 0):
Любое условие, увеличивающее вложенность, стоит раскрыть по Де Моргану
```
if (node['edges'] is not None) or (entropy(node['df']['species']) == 0):
  continue

sample1, sample2, split_feature, best_t = self.find_best_split(node['df'])
if self.check_min_leaf_size == False:
```

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def find_best_split(self, df: pd.DataFrame):
возвращаемый тип

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +    def find_best_split_on_feature(self, feature, df):
типы

2021-12-14 23:46 UTC, ARQtty commented on DecisionTree/decision_tree.py
> +                    if sign == '>=':
У `if sign == '>=':` нет else'а. Зачем этот if?

2021-12-14 23:46 UTC, ARQtty commented on LinearRegression/linreg.py
> +        return model
но ведь `def from_pickle(cls, path: Path) -> None:`

2021-12-14 23:46 UTC, ARQtty commented on LinearRegression/linreg.py
> +    def get_losses(self) -> np.ndarray:
если хочется упороться, можно прочитать про декоратор property. Кажется ты когда-то уже делала getter'ы и setter'ы с его помощью

2021-12-15 13:48 UTC, maypink commented on DecisionTree/decision_tree.py
> +    def check_restrictions(self):
хочу прерывать выполнение и возвращать значения. если я кину, там же ничего не вернется

2021-12-15 13:51 UTC, maypink commented on DecisionTree/decision_tree.py
> +    def check_min_leaf_size(sample1: pd.DataFrame, sample2: pd.DataFrame):
а, ну я сделала их видимо пониже, чем то, про что ты говорил. подняла в функцию

2021-12-16 23:02 UTC, merged